-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.area_indigena
(
    id_area_indigena bigserial NOT NULL,
    nome character varying(50) COLLATE pg_catalog."default" NOT NULL,
    PRIMARY KEY (id_area_indigena),
    UNIQUE (nome)
);

CREATE TABLE IF NOT EXISTS public.cidade
(
    id_cidade bigserial NOT NULL,
    nome character varying(50) COLLATE pg_catalog."default" NOT NULL,
    nome_normalizado character varying(50) COLLATE pg_catalog."default" NOT NULL,
    id_estado bigserial NOT NULL,
    PRIMARY KEY (id_cidade),
    UNIQUE (nome_normalizado, id_estado)
);

CREATE TABLE IF NOT EXISTS public.estado
(
    id_estado bigserial NOT NULL,
    nome character varying(50) COLLATE pg_catalog."default" NOT NULL,
    uf character varying(5) COLLATE pg_catalog."default" NOT NULL,
    PRIMARY KEY (id_estado),
    UNIQUE (uf),
    UNIQUE (nome)
);

CREATE TABLE IF NOT EXISTS public.regiao_administrativa
(
    id_regiao_administrativa bigserial NOT NULL,
    nome character varying(50) COLLATE pg_catalog."default" NOT NULL,
    PRIMARY KEY (id_regiao_administrativa),
    UNIQUE (nome)
);


-- Se der error remover NOT NULL e DEFAULT dos ids estrangeiros de relatorio desmatamento
CREATE TABLE IF NOT EXISTS public.relatorio_desmatamento
(
    id_desmatamento bigserial NOT NULL,
    area_km2 numeric NOT NULL,
    ano integer NOT NULL,
    id_area_indigena bigserial,
    id_cidade bigserial,
    id_unidade_conservacao bigserial,
    PRIMARY KEY (id_desmatamento)
);

CREATE TABLE IF NOT EXISTS public.relatorio_emissao_gases_anual
(
    id_emissao bigserial NOT NULL,
    ano integer NOT NULL,
    co2_1a_ordem numeric,
    co2_2a_ordem numeric,
    co2_por_fogo numeric,
    co2_por_decaimento numeric,
    ch4_eq_fogo numeric,
    n2o_eq_fogo numeric,
    net_co2_1a_ordem numeric,
    net_co2_2a_ordem numeric,
    area_total_secundaria numeric,
    area_cortada numeric,
    co2_emitido_secundaria numeric,
    co2_absorvido_secundaria numeric,
    id_regiao_administrativa bigserial NOT NULL,
    PRIMARY KEY (id_emissao),
    UNIQUE (ano)
);

CREATE TABLE IF NOT EXISTS public.relatorio_focos_queimadas
(
    id_foco_queimada bigserial NOT NULL,
    mes_ano date NOT NULL,
    tipo_area character varying(50) COLLATE pg_catalog."default" NOT NULL,
    quantidade numeric NOT NULL,
    id_estado bigserial NOT NULL,
    PRIMARY KEY (id_foco_queimada)
);

CREATE TABLE IF NOT EXISTS public.relatorio_meteorologia
(
    id_meteorologia bigserial NOT NULL,
    data_horario_coleta timestamp without time zone NOT NULL,
    temperatura_max numeric,
    temperatura_min numeric,
    precipitacao numeric,
    umidade numeric,
    pressao_atm numeric,
    vento_velocidade numeric,
    id_estacao_meteorologica bigserial NOT NULL,
    PRIMARY KEY (id_meteorologia),
    UNIQUE (id_estacao_meteorologica, data_horario_coleta)
);

CREATE TABLE IF NOT EXISTS public.unidade_conservacao
(
    id_unidade_conservacao bigserial NOT NULL,
    nome character varying(100) COLLATE pg_catalog."default" NOT NULL,
    categoria character varying(50) NOT NULL,
    esfera_administrativa character varying(20) NOT NULL,
    tipo character varying(20) NOT NULL,
    area_amazonia_ha numeric NOT NULL,
    id_estado bigserial NOT NULL,
    PRIMARY KEY (id_unidade_conservacao),
    UNIQUE (nome)
);

CREATE TABLE IF NOT EXISTS public.estacao_meteorologica
(
    id_estacao_meteorologica bigserial NOT NULL,
    nome text NOT NULL,
    latitude numeric NOT NULL,
    longitude numeric NOT NULL,
    altitude numeric NOT NULL,
    data_fundacao date NOT NULL,
    id_cidade bigserial NOT NULL,
    PRIMARY KEY (id_estacao_meteorologica),
    UNIQUE (nome)
);

CREATE TABLE IF NOT EXISTS public.cidade_unidade_conservacao
(
    cidade_id_cidade bigserial NOT NULL,
    unidade_conservacao_id_unidade_conservacao bigserial NOT NULL
);

CREATE TABLE IF NOT EXISTS public.estado_regiao_administrativa
(
    estado_id_estado bigserial NOT NULL,
    regiao_administrativa_id_regiao_administrativa bigserial NOT NULL
);

ALTER TABLE IF EXISTS public.cidade
    ADD CONSTRAINT "Cidade_id_estado_fkey" FOREIGN KEY (id_estado)
    REFERENCES public.estado (id_estado) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.relatorio_desmatamento
    ADD CONSTRAINT "RelatorioDesmatamento_id_cidade_fkey" FOREIGN KEY (id_cidade)
    REFERENCES public.cidade (id_cidade) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.relatorio_desmatamento
    ADD CONSTRAINT "RelatorioDesmatamento_id_unidade_conservacao_fkey" FOREIGN KEY (id_unidade_conservacao)
    REFERENCES public.unidade_conservacao (id_unidade_conservacao) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.relatorio_desmatamento
    ADD CONSTRAINT "RelatorioDesmatamento_id_area_indigena_fkey" FOREIGN KEY (id_area_indigena)
    REFERENCES public.area_indigena (id_area_indigena) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.relatorio_emissao_gases_anual
    ADD CONSTRAINT "RelatorioEmissaoGasesAnual_id_regiao_administrativa_fkey" FOREIGN KEY (id_regiao_administrativa)
    REFERENCES public.regiao_administrativa (id_regiao_administrativa) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.relatorio_focos_queimadas
    ADD CONSTRAINT "RelatorioFocosQueimadas_id_estado_fkey" FOREIGN KEY (id_estado)
    REFERENCES public.estado (id_estado) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.relatorio_meteorologia
    ADD CONSTRAINT "RelatorioMeteorologia_id_estacao_meteorologica_fkey" FOREIGN KEY (id_estacao_meteorologica)
    REFERENCES public.estacao_meteorologica (id_estacao_meteorologica) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.unidade_conservacao
    ADD CONSTRAINT "UnidadeConservacao_id_estado_fkey" FOREIGN KEY (id_estado)
    REFERENCES public.estado (id_estado) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.estacao_meteorologica
    ADD CONSTRAINT "EstacaoMeteorologica_id_cidade_fkey" FOREIGN KEY (id_cidade)
    REFERENCES public.cidade (id_cidade) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.cidade_unidade_conservacao
    ADD CONSTRAINT "CidadeUnidadeConservacao_id_cidade_fkey" FOREIGN KEY (cidade_id_cidade)
    REFERENCES public.cidade (id_cidade) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.cidade_unidade_conservacao
    ADD CONSTRAINT "CidadeUnidadeConservacao_id_unidade_conservacao_fkey" FOREIGN KEY (unidade_conservacao_id_unidade_conservacao)
    REFERENCES public.unidade_conservacao (id_unidade_conservacao) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.estado_regiao_administrativa
    ADD CONSTRAINT "EstadoRegiaoAdministrativa_id_estado_fkey" FOREIGN KEY (estado_id_estado)
    REFERENCES public.estado (id_estado) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.estado_regiao_administrativa
    ADD CONSTRAINT "EstadoRegiaoAdministrativa_id_regiao_administrativa_fkey" FOREIGN KEY (regiao_administrativa_id_regiao_administrativa)
    REFERENCES public.regiao_administrativa (id_regiao_administrativa) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS public.relatorio_desmatamento
	ADD CONSTRAINT "RelatorioDesmatamento_fkey_not_all_null_chk"
	CHECK (
	    id_cidade IS NOT NULL OR
	    id_unidade_conservacao IS NOT NULL OR
	    id_area_indigena IS NOT NULL
	);

END;